language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libsdl1.2-dev
    - libjson-glib-dev
    - libglib2.0-dev
    - libgif-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsdl1.2-dev
    - openexr
script:
- make release
- ./upload-to-s3.sh
env:
  global:
  - secure: LBViXO2FEcr7vmP4fPfvfeydlqwMBk7BnLx7pFnXcjOve1m4QBq87yoIYxFqInQHtrnAamMptKZ7cHpj96tdS1rKz/0fBUpZqD0FZcdI1zRC6aDWhiMNkRPY/0HC3qY8A/B0P7cMtmPtyGZArSSsSzzCaMF+tgaDAcswtpqqtN1Hm+DQ914kjhsKEVZGVCU2If38yGTApFzks4YGZmZvJl1c/vWDCQkSXQXsZkdpaPsmmLIv1ysvVdkMBI5lTcNXpScJrc1SF5lcgo2fvhB5xJm/6hqcjrKvlj6nnxto2yJau7nyZScJ32v7DQxYETGB/OBw2Q0wVZa62YC7EkEbK+tNUX0PFdw8kvvDZmrobke8UY+T/SFwAIXZ3+XW5eWzkhGPKO7M4aUlLO70ry3fbWOfPmBk5DJLTjLZIz5auGfeNw5faKEnC+gpRuKKw0smTmchL4twysH0zaSEx1ro63BFhZO1YGLgqdG0WyIKCiaNEiINAlE78gdfVdCbIt9K6BT0A8q7dPnmNSWExafjQ+Gd/smp7K1C9p4KyyrlEKrYYoUHusaDgNP1fCK4amqctRRNDVQ5ySy8xj+/Tf5M+PZXQqKVHmaRoVbrWjWyjnH/orJmvBuQvI/orfFEDDtOz5ZvJlS8vRZWstfgR3gDGhchI0VG7Vm/9x8UCV7YKks=
  - secure: Asja14g4P75G72L+mE3P6bb1UZ+BK8aUIH5sxPbb5ieq0wAB8J6gCxSpamwrlVunMlYUdYesaBgoAWLiSwPXkP3cq6sEY8YVfyuFxMIJ22rPkDoJyLOsjEK0LTUo+d9qV8rVPxqzWpIIoNG2mQH2mMtdP9GUYqR9OIK8SZW1prjdgA4Z43bRFktikipqb5L3gUaVzzmSo48CZ1Kj4Beg9wuqM3n78ObydxAMG7eiqnh+jkvih0Mlx35OY8Cz0++TXow/sVb9DwLDupd/BGcnQPwVAC2ChBXpJJ3LvPfvJhoarbjfuXSN4Ut1PO7fIpZtEQtWrD+E9ebYJ01Ltqr8hiUHaHE8BKzvX2EUsxx/BE2xfYcnBce3L7o5EeOKSFAM5y7OOwbx6lLHMKbK7lgIN5ONUo4GrwHqTebrPt0BSdnk2Yl0NSWNWVgjL3HSt/b7b+23wY/MVo8I2JOi47T6OdDDv57mhfGXXpLsEg1dww73t0fcRQ0vKMNz2xfSuyzXmWcIKtT1sulZuXTLGZJ0T+uWai5NqQ2FgJsaLO48wR/h1TcZfVdrD6ue4npOoO7D/qqKBIRVtAHPSt+R7zhhys/j1sL0JUVZ4eReQVegzMaP8bH+1zsTLIyxFl15mfvTcFJKFiZyO/o8RqaGMolkHSdL3Hg4xZYHO5s5VaRF4AA=
  - secure: VuIs93XGqexI7xrsDL3EflJJqKfKUT4qDn+HvZVqwG8SkZWI9ybUdLuy54Z3L+WNt+j+t4w+Pj5CKvFkSNbZiKFXUJvY97P7LtSehYW8uQmV6VrIY/53UJ7HmUiyPd9A4LtQH45QG0kC2boTd9TKFQz26n6SOjSrUc20Vsx2S0M+I4kAyBCarG6irNaRhowEbHTNUyh7b5/mAls1JoSXfrFXtAXqJ4g2o0qWIZLnqcuos5kt5Svh6ZnLiFaFHh2lP8fITTL+rkAAZfSEJuhRE4k6YwFGu/XhmrmVqXD4++tqScEeo5fPD06yHj62z4DFrke4G6A1qkH/AuuKhxQQEjPtADnnyxBHyGT4e+N03vBFga4vdbQlF2GPxlWuzI1IeEJTZnEJhitQjiyYfS3HfKar4QRK6QCwJKBDAR8Sqbhcq7b0sGrQmjAAM4+d6o36spb6VEQ6FV0lgWHzYm8NoZMaCFEcVQ2LLSI8+1Lr36WP1rIlY5Wk6Hr8ScT/v/t1Tb02j+Cl24sf63CfVRLPgnb1KwnMxKa2Pt03FlDErDz3j5l80p6NTu2vM09LPf11z8ZV6MIZaLh3xBIkh5sx419mfPPLyNDe+Bc8VUq5V7zyixv0wkkP7QrKP0JvVnvwGjbLU1eNGsabJoM60hYwGzi8SxAPkLROPV0mLlX5GPQ=
